### ISSUE TITLE
Not working under website/store view

### ISSUE THREAD

**Issue by refueledinc** [seansan/snh_settings_CategoryParentUrl#4]
When enabling a non-default value, for example multi-site support, urls are not changed. When enabling the default, urls change. Does this extension not support multi-store or even just store view?

**Comment by refueledinc** [comment]
The following change seems to have fixed the issue for use with limited testing:
https://github.com/seansan/snh_settings_CategoryParentUrl/blob/master/app/code/community/SNH/CategoryParentUrl/Model/Url.php#L9-L12

Change to:
```
$storeId = $category->getStoreId();
$configValue = Mage::getStoreConfig('catalog/seo/category_use_parentcategory', $storeId);
if (!$configValue) {return parent::getCategoryRequestPath($category, $parentPath);}

$idPath  = $this->generatePath('id', null, $category);
$suffix  = $this->getCategoryUrlSuffix($storeId);
```

**Comment by seansan** [comment]
thank fixed
