### ISSUE TITLE
Got mixed results...

### ISSUE THREAD

**Issue by d3viliz3d** [seansan/snh_settings_CategoryParentUrl#7]
Hi! I installed the extension and it seems to work fine for the most part, but if I open the product I can still see its category.
Example website/category/product

The funny part is that if I go to website/product, I can see the product just fine. But how can I remove the parent category from the url during the normal navigation?

Thanks!

**Comment by seansan** [comment]
Did you reindex?

Sent from my iPhone.

On 22 Jul 2016, at 05:27, d3viliz3d notifications@github.com wrote:

Hi! I installed the extension and it seems to work fine for the most part, but if I open the product I can still see its category.
Example website/category/product

The funny part is that if I go to website/product, I can see the product just fine. But how can I remove the parent category from the url during the normal navigation?

Thanks!
